[workspace]

members = [
    "consensus",
    "types",
    "crypto",
    "rmc",
    "mock",

    # Example crates.
    "examples/dummy_honest",
    "examples/blockchain",
]

exclude = [
    "fuzz",
]
