[workspace]

members = [

    # Published packages
    "consensus",
    "types",
    "crypto",
    "rmc",
    "mock",

    # Examples
    "examples/ordering",
    "examples/blockchain",

    # Fuzzing
    "fuzz"

]

[profile.test]
opt-level = 3
