[workspace]

members = [

    # Published packages
    "consensus",
    "types",
    "crypto",
    "rmc",
    "mock",

    # Examples
    "examples/crash_recovery",
    "examples/blockchain",

    # Fuzzing
    "fuzz"

]
