[book]
authors = ["Cardinal Cryptography"]
language = "en"
description = "Documentation of the Rust implementation of Aleph protocol"
multilingual = false
title = "AlephBFT"

[build]
create-missing = false
