name: Version bump check for code changes in the aleph-bft package

on:
  pull_request:
    branches:
      - main
    paths:
      - 'consensus/src/**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if version bumped for 'consensus'
        uses: ./.github/actions/check-version-bumped
        with:
          cargo-toml-path: consensus/Cargo.toml
