name: Post DoD checklist
on: [pull_request_target]
jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            Please make sure the following happened
            - [ ] Appropriate tests created
            - [ ] Infrastructure updated accordingly
            - [ ] Updated existing documentation
            - [ ] New documentation created
            - [ ] Version bumped if breaking changes
