name: Publish to crates.io

on:
  push:
    branches:
      - main

jobs:
  publish:
    environment: Autobump version
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Cardinal-Cryptography/AlephBFT'}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-rust-toolchain
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
          ignore-unpublished-changes: true
          publish-delay: 30000
