name: Publish to crates.io

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'

jobs:
  publish:
    # need to rename environment name after this is merged
    environment: Autobump version
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Cardinal-Cryptography/AlephBFT'}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: credentials
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - name: publish
        run: |
          if git diff HEAD~ -- Cargo.toml | grep -q '^+version ='; then
            echo "Version in Cargo.toml was bumped in this PR, publishing to crates.io."
            cargo publish
          fi
