name: Autobump version

on:
  workflow_dispatch:
  # NOTE: changed to "manual workflow dispatch" for now.
  # TODO: To be automated again, when workflows stabilize
  # and pushes to main origin will be forbidden.
  #  push:
  #    branches:
  #    - main



jobs:
  autobump:
    environment: Autobump version
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Cardinal-Cryptography/AlephBFT'}}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: credentials
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - name: publish
        run: |
          echo 'Uploading to crates.io'
          cargo publish

