name: Autobump version

on:
  push:
    branches:
    - main

jobs:
  autobump:
    environment: Autobump version
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Cardinal-Cryptography/AlephBFT'}}
    steps:
      - name: publish
        run: |
          cargo publish

