name: Autobump version

on:
  push:
    branches:
    - main

jobs:
  autobump:
    environment: Autobump version
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Cardinal-Cryptography/AlephBFT'}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: bump
        run: |
          version=`grep -e '^version =' Cargo.toml | sed 's/version = //' | sed 's/"//g'`
          major_version=`echo $version|grep -o -e '^[0-9]*'`
          minor_version=`echo $version|grep -o -e '^[0-9]*.[0-9]*'|grep -o -e '[0-9]*$'`
          patch_version=`echo $version|grep -o -e '[0-9]*$'`
          git config user.email "<>"
          git config user.name "Version autobump"
          if git diff HEAD~ -- Cargo.toml | grep -q '^+version ='; then
            echo 'Version has been bumped manually, bumping readme version and uploading to crates.io'
            new_version=$major_version.$minor_version
            sed -i "s/aleph-bft = \"\^[0-9]*.[0-9]*\"$/aleph-bft = \"^$new_version\"/"  README.md
            git add README.md
            git commit --amend --no-edit
            git push -f origin main
            touch publishMe
            exit 0
          fi
          if [ -e `git diff HEAD~ -- src/` ]; then
            echo 'No changes in code.'
            exit 0
          fi
          new_version=$major_version.$minor_version.$((patch_version + 1))
          sed -i "s/^version = \"$version\"$/version = \"$new_version\"/" Cargo.toml
          git add Cargo.toml
          git commit --amend --no-edit
          git push -f origin main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: credentials
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - name: publish
        run: |
          if [ -f publishMe ]; then
            cargo publish
          fi
